### ISSUE TITLE
Does not use `printWidth` from package.json with `--keep-indentation`

### ISSUE THREAD

**Issue by raine** [josephfrazier/prettier_d#8] opened 2018-06-18 16:38 UTC
```
$ prettier_d --pkg-conf --keep-indentation path/to/file
Error: Invalid `"printWidth"` value. Expected an integer, but received `null`.
```

- `package.json` has `printWidth` set, other values are respected when prettier_d is used without `-keep-indentation`
- `prettier_d` is installed globally, installing `prettier` in the project had no impact

**Comment by josephfrazier** [comment] 2018-06-19 15:04
Hi @raine, thanks for reporting these issues!

`--keep-indentation` is a bit of a hack, and I recommend not using it (see https://github.com/prettier/prettier/pull/1577 for more discussion). Can you explain your use case a little more? It looks like you're formatting an entire file, so I'm wondering why you're using `--keep-indentation` in the first place...

---

> - `prettier_d` is installed globally, installing `prettier` in the project had no impact

Could you make a separate issue for this, assuming it's independent of the `printWidth` problem?

**Comment by raine** [comment] 2018-06-19 15:06
Use case is using `prettier_d` in vim, where it may format part of file only. The same problem appears there, but I used command line here to reproduce.

edit: I'm using neoformat plugin in vim to use `prettier_d`

edit2: Maybe I should make an issue on neoformat for retaining indent level if only formatting a part of the file.

**Comment by josephfrazier** [comment] 2018-06-19 15:16
Ok, that makes sense. It looks like `vim-prettier` has added support for this, using Prettier's newer `--range-start` and `--range-end` options (see https://github.com/prettier/vim-prettier/pull/78#issuecomment-394246510), so that could be a potential option. However, I think that using this would require that https://github.com/josephfrazier/prettier_d/issues/4#issuecomment-327044292 be done first, and I'm not sure how much time I have to make that happen.

---

Is the project you're testing this on publicly available? I might be able to track down and fix the error you're seeing, if I can reproduce it:

```
Error: Invalid `"printWidth"` value. Expected an integer, but received `null`.
```

**Comment by josephfrazier** [comment] 2018-12-27 15:04
Closing this, as I'm planning to make `prettier_d` simply a wrapper around Prettier, without supporting any extra options. See here for details: https://github.com/josephfrazier/prettier_d/issues/4#issuecomment-450060928

**Closed as completed by josephfrazier** 2018-12-27 15:04 UTC
