### ISSUE TITLE
Uses very old prettier version

### ISSUE THREAD

**Issue by flybayer** [josephfrazier/prettier_d#10] opened 2018-12-01 16:29 UTC
Hey Joseph, I love using prettier_d! The only problem is it's stuck on a very old version of Prettier.

Is there anyway to fix this on my side?

Ideally prettier_d would only require prettier as a peer dependency so I can manage the prettier version myself. This makes it easier to test pre-release versions, etc.

Thanks!

```bash
$ prettier_d -v
v1.14.0 (prettier_d v5.7.4)
```

**Comment by josephfrazier** [comment] 2018-12-16 22:58
Hi @flybayer, glad to hear you enjoy using prettier_d! This issue is similar to #4, where I wrote some notes on what would be involved with upgrading Prettier. The idea there was to bundle the latest version and always use it, but I think similar changes would be required to support Prettier as a peer dependency, since we'd need to forward all arguments to Prettier as-is, instead of hard-coding a particular set of supported arguments. What do you think?

**Comment by flybayer** [comment] 2018-12-17 15:30
Yes, I think if possible it's best to have prettier_d be as slim as possible and forward everything to prettier.

**Comment by josephfrazier** [comment] 2018-12-23 17:34
Thanks for clarifying, I'm going to go ahead and close this as a duplicate of https://github.com/josephfrazier/prettier_d/issues/4

**Closed as completed by josephfrazier** 2018-12-23 17:34 UTC
